### ISSUE TITLE
Can I add a picker and writer method to this plugin?

### ISSUE THREAD

**Issue by jiajiabingcheng** [fluttercommunity/flutter_contacts#14]
Hi Clovis, 

Nice plugin! In my app I want to pick a single contact from the device phone book (launch the device phone book page) and export one contact to the device phone book (open the device contact edit page). Can I pr to add these two methods to your plugin?

Also I find there's no permission check and request dialog in this plugin, can I add this part too? Something like:

`if (readStoragePermission != PackageManager.PERMISSION_GRANTED) {
 activity.requestPermissions(new String[]{Manifest.permission.READ_CONTACTS}, REQUEST_READ_CONTACTS);
} else {
     Start to pick a contact 
}`

Thanks :]

**Comment by clovisnicolas** [comment]
Hello,

Yes I guess it would be nice to have something like pickContact / openContactForm 😃 

However, I suggest that people use [flutter_simple_permisssions](https://github.com/AppleEducate/flutter_simple_permissions) to handle permissions. This ensures they are handled the same way for all plugins, instead of each plugin providing his own custom way to check for permissions.

**Comment by jiajiabingcheng** [comment]
Great! Thanks :]
