### ISSUE TITLE
Android crashes few seconds after getting all contacts

### ISSUE THREAD

**Issue by olaray** [fluttercommunity/flutter_contacts#21]
D/AndroidRuntime(11912): Shutting down VM
E/AndroidRuntime(11912): FATAL EXCEPTION: main
E/AndroidRuntime(11912): Process: com.appzonegroup.zone, PID: 11912
E/AndroidRuntime(11912): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(11912):        at io.flutter.view.FlutterNativeView$1.reply(FlutterNativeView.java:146)
E/AndroidRuntime(11912):        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:194)
E/AndroidRuntime(11912):        at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin$GetContactsTask.onPostExecute(ContactsServicePlugin.java:134)
E/AndroidRuntime(11912):        at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin$GetContactsTask.onPostExecute(ContactsServicePlugin.java:115)
E/AndroidRuntime(11912):        at android.os.AsyncTask.finish(AsyncTask.java:667)
E/AndroidRuntime(11912):        at android.os.AsyncTask.-wrap1(AsyncTask.java)
E/AndroidRuntime(11912):        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
E/AndroidRuntime(11912):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(11912):        at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime(11912):        at android.app.ActivityThread.main(ActivityThread.java:6816)
E/AndroidRuntime(11912):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11912):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
E/AndroidRuntime(11912):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)

**Comment by zoechi** [comment]
please add the output of `flutter doctor`

**Comment by olaray** [comment]
[✓] Flutter (Channel beta, v0.4.4, on Mac OS X 10.13.4 17E202, locale en-NG)    • Flutter version 0.4.4 at /Users/Zone1/Downloads/flutter    • Framework revision f9bb4289e9 (4 weeks ago), 2018-05-11 21:44:54 -0700
    • Engine revision 06afdfe54e
    • Dart version 2.0.0-dev.54.0.flutter-46ab040e58

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/Zone1/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/Zone1/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 24.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.23.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.12.1

[✓] Connected devices (2 available)
    • SM C9000 • a5a85845                             • android-arm64 • Android 7.1.1 (API 25)
    • iPhone X • 52A0626F-AF0E-41E2-8BBA-AC49F2433C2A • ios           • iOS 11.3 (simulator)

• No issues found!

**Comment by zoechi** [comment]
And you are you using the latest plugin version?

**Comment by olaray** [comment]
Yes I am. The version i am using is `contacts_service: "^0.0.6"`

**Comment by erik-seifert** [comment]
Same to me

[✓] Flutter (Channel beta, v0.4.4, on Linux, locale en_US.UTF-8)
    • Flutter version 0.4.4 at /home/erik/projects/flutter/flutter
    • Framework revision f9bb4289e9 (5 weeks ago), 2018-05-11 21:44:54 -0700
    • Engine revision 06afdfe54e
    • Dart version 2.0.0-dev.54.0.flutter-46ab040e58

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/erik/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /home/erik/projects/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /home/erik/projects/android-studio
    • Flutter plugin version 23.1.2
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] VS Code (version 1.24.1)
    • VS Code at /usr/share/code
    • Dart Code extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code

[✓] Connected devices (1 available)
    • F5321 • BH901GN05Z • android-arm64 • Android 8.0.0 (API 26)

! Doctor found issues in 1 category.

**Comment by erik-seifert** [comment]
is there any progress ?

**Comment by olaray** [comment]
I created a PR on this already...

https://github.com/clovisnicolas/flutter_contacts/pull/22

**Comment by osamagamal65** [comment]
this issue happens when the function called for the sceond time  (when i install the package for the first time it runs well, however when trying to run  get contacts later this issue seems to happen )


Shutting down VM
E/AndroidRuntime( 6142): FATAL EXCEPTION: main
E/AndroidRuntime( 6142): Process: com.cloudsoft.pecards, PID: 6142
E/AndroidRuntime( 6142): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime( 6142): 	at io.flutter.view.FlutterNativeView$1.reply(FlutterNativeView.java:176)
E/AndroidRuntime( 6142): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:194)
E/AndroidRuntime( 6142): 	at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin$GetContactsTask.onPostExecute(ContactsServicePlugin.java:134)
E/AndroidRuntime( 6142): 	at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin$GetContactsTask.onPostExecute(ContactsServicePlugin.java:115)
E/AndroidRuntime( 6142): 	at android.os.AsyncTask.finish(AsyncTask.java:667)
E/AndroidRuntime( 6142): 	at android.os.AsyncTask.-wrap1(AsyncTask.java)
E/AndroidRuntime( 6142): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
E/AndroidRuntime( 6142): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 6142): 	at android.os.Looper.loop(Looper.java:163)
E/AndroidRuntime( 6142): 	at android.app.ActivityThread.main(ActivityThread.java:6383)
E/AndroidRuntime( 6142): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6142): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/AndroidRuntime( 6142): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

Running flutter doctor: 
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, v0.5.8, on Microsoft Windows [Version 10.0.17134.165], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.1)
[√] VS Code, 64-bit edition (version 1.26.1)
[√] Connected devices (1 available)

the plugin version is  contacts_service: ^0.0.8

**Comment by wal33d006** [comment]
Same goes for me. Using ^0.0.8. Android crashes immediately. iOS not even building. Saying that it requires an older version of Swift.

**Comment by wal33d006** [comment]
This is the log. App opens and crashes immediately. 
Running 'gradlew assembleDebug'...
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
I/FlutterActivityDelegate( 7471): onResume setting current activity to this
Syncing files to device Android SDK built for x86 64...
E/AndroidRuntime( 7471): FATAL EXCEPTION: AsyncTask #2
E/AndroidRuntime( 7471): Process: com.example.contacttest, PID: 7471
E/AndroidRuntime( 7471): java.lang.RuntimeException: An error occurred while executing doInBackground()
E/AndroidRuntime( 7471): 	at android.os.AsyncTask$3.done(AsyncTask.java:309)
E/AndroidRuntime( 7471): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
E/AndroidRuntime( 7471): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
E/AndroidRuntime( 7471): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/AndroidRuntime( 7471): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
E/AndroidRuntime( 7471): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
E/AndroidRuntime( 7471): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
E/AndroidRuntime( 7471): 	at java.lang.Thread.run(Thread.java:818)
E/AndroidRuntime( 7471): Caused by: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.contacts.ContactsProvider2 from ProcessRecord{6c9c866 7471:com.example.contacttest/u0a64} (pid=7471, uid=10064) requires android.permission.READ_CONTACTS or android.permission.WRITE_CONTACTS
E/AndroidRuntime( 7471): 	at android.os.Parcel.readException(Parcel.java:1599)
E/AndroidRuntime( 7471): 	at android.os.Parcel.readException(Parcel.java:1552)
E/AndroidRuntime( 7471): 	at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:3550)
E/AndroidRuntime( 7471): 	at android.app.ActivityThread.acquireProvider(ActivityThread.java:4778)
E/AndroidRuntime( 7471): 	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2018)
E/AndroidRuntime( 7471): 	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1468)
E/AndroidRuntime( 7471): 	at android.content.ContentResolver.query(ContentResolver.java:475)
E/AndroidRuntime( 7471): 	at android.content.ContentResolver.query(ContentResolver.java:434)
E/AndroidRuntime( 7471): 	at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin.getCursor(ContactsServicePlugin.java:145)
E/AndroidRuntime( 7471): 	at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin.access$100(ContactsServicePlugin.java:34)
E/AndroidRuntime( 7471): 	at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin$GetContactsTask.doInBackground(ContactsServicePlugin.java:120)
E/AndroidRuntime( 7471): 	at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin$GetContactsTask.doInBackground(ContactsServicePlugin.java:115)
E/AndroidRuntime( 7471): 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
E/AndroidRuntime( 7471): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime( 7471): 	... 4 more
D/        ( 7471): HostConnection::get() New Host Connection established 0x7f59f711abc0, tid 7489
D/EGL_emulation( 7471): eglMakeCurrent: 0x7f59f7115b80: ver 2 0 (tinfo 0x7f59fab42860)
E/Surface ( 7471): getSlotFromBufferLocked: unknown buffer: 0x7f59ec416e80
D/EGL_emulation( 7471): eglMakeCurrent: 0x7f59fab74b40: ver 2 0 (tinfo 0x7f59fab52b80)
E/Surface ( 7471): getSlotFromBufferLocked: unknown buffer: 0x7f59fab74e60
W/art     ( 7471): Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[15,tid=7488,Native,Thread*=0x7f59e9689000,peer=0x12da70a0,"Thread-284"]
No isolates found after VM start: 0
I/Process ( 7471): Sending signal. PID: 7471 SIG: 9
Application finished.

**Comment by wal33d006** [comment]
@olaray @b-connect @osamagamal65 
It's working. For iOS, you need to create flutter project like this => flutter create -i swift your_app_name.
In android if it's crashing, just go to android settings and enable the contacts permission in app management. 
You need to integrate a permissions plugin in the app in order to get permission through code.
