### ISSUE TITLE
Request: Update contact

### ISSUE THREAD

**Issue by korenzerah** [fluttercommunity/flutter_contacts#43]
Hello,
I wanted to ask if there is any intention to develop the update contact feature?
Currently I just delete and re-add the contact to the user, but the problem with that (specifically on Android) is that the new contact is being added to the user's device, and the previous contact might had been on his Google account. I think this feature is required in general.
Really appreciating this plugin!
Thanks ahead.

**Comment by clovisnicolas** [comment]
Hello, I'm afraid I won't have time to work on this anytime soon.

**Comment by lukasgit** [comment]
@clovisnicolas Would you be willing to allow one of us to manage this repo?

**Comment by clovisnicolas** [comment]
@lukasgit i'll try to have it moved to fluttercommunity @slightfoot

**Comment by slightfoot** [comment]
hey @clovisnicolas email community@flutter.zone to take this further.

**Comment by korenzerah** [comment]
Any update?

**Comment by clovisnicolas** [comment]
Haven't received a reply from flutter community yet

**Comment by clovisnicolas** [comment]
@korenzerah project has been moved to fluttercommunity, feel free to join and contribute

**Comment by korenzerah** [comment]
@clovisnicolas Thanks!
And of course thanks for the library in general, already have a production app using your library :)

**Comment by jeroen-meijer** [comment]
Great work on the package.
We are currently looking for people who are willing to 'adopt' this package and become it's maintainer, either for further development and/or to update it when Flutter or Dart updates.

If any of you want to do so, please contact us in this issue, [by email](community@flutter.zone) or in the Study Group.

I'll leave this issue open since the request feature has not been planned or answered yet.

**Comment by lukasgit** [comment]
@jeroen-meijer I sent you an email

**Comment by jeroen-meijer** [comment]
@lukasgit is now owner and maintainer for this package.
